version: '3'
services:
  nestjs:
    build: ./
    # image: 151268123722.dkr.ecr.ap-northeast-1.amazonaws.com/nestjs-sample:1.0.0
    ports:
      - "3000:3000"
    # depends_on:
    #   - mysqldb
    hostname: api-server
    # environment:
    #   HOSTNAME: '0.0.0.0'
    #   DATABASE_WRITER_HOST: 'api-server'
    #   DATABASE_READER_HOST: 'api-server'
    #   DATABASE_USER: 'admin'
    #   DATABASE_PASSWOED: 'admin'

  # sonarqube:
  #   image: sonarqube:lts-community
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - SONAR_JDBC_URL=jdbc:postgresql://postgres-server:5432/sonar
  #     - SONAR_JDBC_USERNAME=sonar
  #     - SONAR_JDBC_PASSWORD=Test12345
  #   hostname: sonar-server

  # postgres:
  #   image: postgres
  #   hostname: postgres-server
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=Test12345
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080